In [1]:
# Autoreload all modules
%load_ext autoreload
%autoreload 2

import numpy as np
import jax
import jax.numpy as jnp
import jax.random as jr
from flax.training import train_state
import optax
import matplotlib.pyplot as plt

import sys
sys.path.append('../../')
sys.path.append('../../mcjax/process')

from mcjax.proba.gaussian import IsotropicGauss, Gauss
from mcjax.proba.doublewell import DoubleWell
from mcjax.process.models import MLPModel, ResBlockModel
from mcjax.process.ou import OU
from mcjax.process.algo import DDSAlgorithm,IDEMAlgorithm,PISAlgorithm, ControlledMonteCarloDiffusion

### Test DoubleWell Distribution

Unnormalized density:
$$
    \rho(x) = \exp( -\sum_{i=1}^m (x_i^2 - \delta)^2 - 1/2 \sum_{i=m+1}^d x_i^2 )
$$

In [2]:
dw = DoubleWell(dim=5, m=5, delta=4.0)

In [5]:
# generate a random batch x1 of dim 5
key = jr.PRNGKey(0)
x1 = jr.normal(key, (10, 5))*2.0
print("Sample from normal distribution:", x1)
logp = dw.batch(x1)
print("Log probability of the samples:", logp)


Sample from normal distribution: [[ 3.2452843   4.0505295  -0.8671889  -0.1572347   0.3521818 ]
 [-1.9441785  -0.9905975   0.9887572   1.3286986  -1.900327  ]
 [ 4.359061   -3.9103012   0.71714145  0.31559026  2.5541694 ]
 [ 3.0209296   1.941312    1.1992161   0.04940141 -3.8329544 ]
 [-3.7186983   3.456288    0.0943807   1.628256    0.26265535]
 [ 0.5656941   2.4871886   1.3805602  -1.6014749  -1.48198   ]
 [-3.0776575   0.6053837  -0.04143209  0.22657442 -0.4413094 ]
 [ 0.14104512  1.7065916  -1.6435477  -0.02922842 -0.30092433]
 [-1.8002704  -1.5181454   0.66619027  1.6184981   0.08538511]
 [-1.1553425  -0.8287979  -3.8825066   2.6322367   1.5085456 ]]
Log probability of the samples: [-237.96912   -23.440172 -386.24948  -163.18228  -192.94234   -28.019941
  -89.203026  -49.98768   -33.94384  -152.26039 ]
